-- Databricks notebook source
-- MAGIC %md
-- MAGIC # NYC yellow taxi trips - January 2024 - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/`. Executed on a serverless SQL warehouse.
-- MAGIC
-- MAGIC 1. Upload the full raw files to the Unity Catalog volume `/Volumes/workspace/da_learn_15/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse (or DBR 13.3+) and *Run all*.
-- MAGIC 3. Cells: config -> 01 staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data quality -> visual queries.

-- COMMAND ----------

-- Config
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_15;
CREATE VOLUME IF NOT EXISTS workspace.da_learn_15.raw;
USE CATALOG workspace;
USE SCHEMA da_learn_15;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging (raw landing, no type inference for CSV; casting happens in 02)

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_trips AS
SELECT * FROM read_files('/Volumes/workspace/da_learn_15/raw/yellow_tripdata_2024-01.parquet', format => 'parquet');

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_zones AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_15/raw/taxi_zone_lookup.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; DuckDB via 00 shims)

CREATE OR REPLACE TABLE cln_zones AS
SELECT TRY_CAST(LocationID AS INT) AS location_id, trim(Borough) AS borough, trim(Zone) AS zone, trim(service_zone) AS service_zone
FROM stg_zones WHERE TRY_CAST(LocationID AS INT) IS NOT NULL;

-- COMMAND ----------

CREATE OR REPLACE TABLE cln_trips_flagged AS
WITH t AS (
  SELECT
    TRY_CAST(VendorID AS INT)                         AS vendor_id,
    CAST(tpep_pickup_datetime AS TIMESTAMP)           AS pickup_ts,
    CAST(tpep_dropoff_datetime AS TIMESTAMP)          AS dropoff_ts,
    TRY_CAST(passenger_count AS INT)                  AS passenger_count,
    TRY_CAST(trip_distance AS DOUBLE)                 AS trip_distance,
    TRY_CAST(RatecodeID AS INT)                       AS ratecode_id,
    TRY_CAST(PULocationID AS INT)                     AS pu_location_id,
    TRY_CAST(DOLocationID AS INT)                     AS do_location_id,
    TRY_CAST(payment_type AS INT)                     AS payment_type,
    TRY_CAST(fare_amount AS DOUBLE)                   AS fare_amount,
    TRY_CAST(extra AS DOUBLE)                         AS extra,
    TRY_CAST(mta_tax AS DOUBLE)                       AS mta_tax,
    TRY_CAST(tip_amount AS DOUBLE)                    AS tip_amount,
    TRY_CAST(tolls_amount AS DOUBLE)                  AS tolls_amount,
    TRY_CAST(improvement_surcharge AS DOUBLE)         AS improvement_surcharge,
    TRY_CAST(congestion_surcharge AS DOUBLE)          AS congestion_surcharge,
    TRY_CAST(Airport_fee AS DOUBLE)                   AS airport_fee,
    TRY_CAST(total_amount AS DOUBLE)                  AS total_amount
  FROM stg_trips
), d AS (
  SELECT *, (unix_timestamp(dropoff_ts) - unix_timestamp(pickup_ts)) / 60.0 AS duration_min FROM t
)
SELECT d.*,
  CASE WHEN pickup_ts < TIMESTAMP'2024-01-01 00:00:00' OR pickup_ts >= TIMESTAMP'2024-02-01 00:00:00' THEN 1 ELSE 0 END AS dq_outside_month,
  CASE WHEN duration_min < 1 OR duration_min > 180 THEN 1 ELSE 0 END                                  AS dq_bad_duration,
  CASE WHEN trip_distance IS NULL OR trip_distance <= 0 OR trip_distance > 100 THEN 1 ELSE 0 END      AS dq_bad_distance,
  CASE WHEN fare_amount IS NULL OR fare_amount <= 0 OR total_amount <= 0 OR fare_amount > 500 THEN 1 ELSE 0 END AS dq_bad_amount,
  CASE WHEN trip_distance > 0 AND duration_min > 0 AND trip_distance / (duration_min / 60.0) > 80 THEN 1 ELSE 0 END AS dq_speed_outlier,
  CASE WHEN payment_type = 0 OR payment_type IS NULL THEN 1 ELSE 0 END                                AS dq_unknown_payment
FROM d;

-- COMMAND ----------

CREATE OR REPLACE TABLE cln_trips AS
SELECT * FROM cln_trips_flagged
WHERE dq_outside_month = 0 AND dq_bad_duration = 0 AND dq_bad_distance = 0 AND dq_bad_amount = 0 AND dq_speed_outlier = 0;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema: fact_trips (one row per valid trip) + dim_zone, dim_date, dim_payment, dim_ratecode, dim_vendor.

CREATE OR REPLACE TABLE dim_zone AS
SELECT location_id, borough, zone, service_zone,
       CASE WHEN zone IN ('JFK Airport', 'LaGuardia Airport', 'Newark Airport') THEN 1 ELSE 0 END AS is_airport
FROM cln_zones;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_payment AS
SELECT * FROM (VALUES (0, 'Flex fare / unknown'), (1, 'Credit card'), (2, 'Cash'), (3, 'No charge'), (4, 'Dispute'),
                      (5, 'Unknown'), (6, 'Voided trip')) AS t(payment_type, payment_name);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_ratecode AS
SELECT * FROM (VALUES (1, 'Standard'), (2, 'JFK flat fare'), (3, 'Newark'), (4, 'Nassau/Westchester'),
                      (5, 'Negotiated'), (6, 'Group ride'), (99, 'Unknown')) AS t(ratecode_id, ratecode_name);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_vendor AS
SELECT * FROM (VALUES (1, 'Creative Mobile Technologies'), (2, 'Curb Mobility (VeriFone)'), (6, 'Myle Technologies')) AS t(vendor_id, vendor_name);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_date AS
SELECT DISTINCT CAST(year(pickup_ts) * 10000 + month(pickup_ts) * 100 + day(pickup_ts) AS INT) AS date_key,
  CAST(pickup_ts AS DATE) AS trip_date, dayofweek(pickup_ts) AS day_of_week,
  CASE dayofweek(pickup_ts) WHEN 1 THEN 'Sun' WHEN 2 THEN 'Mon' WHEN 3 THEN 'Tue' WHEN 4 THEN 'Wed'
       WHEN 5 THEN 'Thu' WHEN 6 THEN 'Fri' ELSE 'Sat' END AS day_name,
  CASE WHEN dayofweek(pickup_ts) IN (1, 7) THEN 1 ELSE 0 END AS is_weekend
FROM cln_trips;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_trips AS
SELECT
  CAST(year(pickup_ts) * 10000 + month(pickup_ts) * 100 + day(pickup_ts) AS INT) AS date_key,
  hour(pickup_ts) AS pickup_hour, pickup_ts, dropoff_ts,
  pu_location_id, do_location_id, vendor_id, COALESCE(ratecode_id, 99) AS ratecode_id, payment_type,
  passenger_count, trip_distance, ROUND(duration_min, 2) AS duration_min,
  fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge,
  congestion_surcharge, airport_fee, total_amount, dq_unknown_payment
FROM cln_trips;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  KPIs and business questions (valid trips only)

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT COUNT(*) AS trips,
  ROUND(COUNT(*) / COUNT(DISTINCT f.date_key), 0) AS avg_trips_per_day,
  ROUND(SUM(f.total_amount), 2) AS gross_revenue,
  ROUND(AVG(f.fare_amount), 2) AS avg_fare,
  ROUND(AVG(f.total_amount), 2) AS avg_total,
  ROUND(AVG(f.trip_distance), 2) AS avg_distance_mi,
  ROUND(AVG(f.duration_min), 2) AS avg_duration_min,
  ROUND(100.0 * SUM(CASE WHEN f.payment_type = 1 THEN f.tip_amount END) / SUM(CASE WHEN f.payment_type = 1 THEN f.fare_amount END), 2) AS card_tip_pct_of_fare,
  ROUND(100.0 * AVG(CASE WHEN f.payment_type = 1 THEN 1.0 ELSE 0.0 END), 2) AS card_share_pct,
  ROUND(100.0 * AVG(CASE WHEN z.is_airport = 1 THEN 1.0 ELSE 0.0 END), 2) AS airport_pickup_share_pct
FROM fact_trips f LEFT JOIN dim_zone z ON z.location_id = f.pu_location_id;

-- COMMAND ----------

-- Q1: demand by hour of day (weekday vs weekend averages per day)

CREATE OR REPLACE TABLE a_hourly AS
WITH n AS (SELECT SUM(1 - is_weekend) AS weekdays, SUM(is_weekend) AS weekend_days FROM dim_date)
SELECT f.pickup_hour, COUNT(*) AS trips,
  ROUND(SUM(CASE WHEN d.is_weekend = 0 THEN 1 ELSE 0 END) / NULLIF(MAX(n.weekdays), 0), 1) AS avg_weekday_trips,
  ROUND(SUM(CASE WHEN d.is_weekend = 1 THEN 1 ELSE 0 END) / NULLIF(MAX(n.weekend_days), 0), 1) AS avg_weekend_trips,
  ROUND(AVG(f.fare_amount), 2) AS avg_fare,
  ROUND(SUM(f.trip_distance) / (SUM(f.duration_min) / 60.0), 2) AS avg_speed_mph
FROM fact_trips f JOIN dim_date d ON d.date_key = f.date_key CROSS JOIN n
GROUP BY f.pickup_hour;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_daily AS
SELECT d.trip_date, d.day_name, COUNT(*) AS trips, ROUND(SUM(f.total_amount), 2) AS revenue
FROM fact_trips f JOIN dim_date d ON d.date_key = f.date_key
GROUP BY d.trip_date, d.day_name;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_day_of_week AS
SELECT d.day_of_week, d.day_name, COUNT(*) AS trips, COUNT(DISTINCT d.date_key) AS days,
  ROUND(COUNT(*) / COUNT(DISTINCT d.date_key), 0) AS avg_trips_per_day
FROM fact_trips f JOIN dim_date d ON d.date_key = f.date_key
GROUP BY d.day_of_week, d.day_name;

-- COMMAND ----------

-- Q2: where - pickup zones and boroughs

CREATE OR REPLACE TABLE a_pickup_zones AS
SELECT z.zone, z.borough, COUNT(*) AS trips, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS share_pct,
  ROUND(AVG(f.fare_amount), 2) AS avg_fare, ROUND(AVG(f.trip_distance), 2) AS avg_distance_mi
FROM fact_trips f JOIN dim_zone z ON z.location_id = f.pu_location_id
GROUP BY z.zone, z.borough;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_borough AS
SELECT z.borough AS pickup_borough, COUNT(*) AS trips, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS share_pct,
  ROUND(AVG(f.fare_amount), 2) AS avg_fare, ROUND(AVG(f.trip_distance), 2) AS avg_distance_mi,
  ROUND(100.0 * SUM(CASE WHEN f.payment_type = 1 THEN f.tip_amount END) / SUM(CASE WHEN f.payment_type = 1 THEN f.fare_amount END), 2) AS card_tip_pct
FROM fact_trips f JOIN dim_zone z ON z.location_id = f.pu_location_id
GROUP BY z.borough;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_od_pairs AS
SELECT pz.zone AS pickup_zone, dz.zone AS dropoff_zone, COUNT(*) AS trips, ROUND(AVG(f.fare_amount), 2) AS avg_fare
FROM fact_trips f JOIN dim_zone pz ON pz.location_id = f.pu_location_id JOIN dim_zone dz ON dz.location_id = f.do_location_id
GROUP BY pz.zone, dz.zone
ORDER BY trips DESC, pickup_zone, dropoff_zone
LIMIT 15;

-- COMMAND ----------

-- Q3: fares and tips

CREATE OR REPLACE TABLE a_payment AS
SELECT p.payment_name, COUNT(*) AS trips, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS share_pct,
  ROUND(AVG(f.total_amount), 2) AS avg_total, ROUND(100.0 * SUM(f.tip_amount) / NULLIF(SUM(f.fare_amount), 0), 2) AS tip_pct_of_fare
FROM fact_trips f JOIN dim_payment p ON p.payment_type = f.payment_type
GROUP BY p.payment_name;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_distance_bands AS
SELECT CASE WHEN trip_distance < 1 THEN '1 <1 mi' WHEN trip_distance < 2 THEN '2 1-2 mi' WHEN trip_distance < 5 THEN '3 2-5 mi'
            WHEN trip_distance < 10 THEN '4 5-10 mi' WHEN trip_distance < 20 THEN '5 10-20 mi' ELSE '6 20+ mi' END AS distance_band,
  COUNT(*) AS trips, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS share_pct,
  ROUND(AVG(fare_amount), 2) AS avg_fare, ROUND(SUM(fare_amount) / SUM(trip_distance), 2) AS fare_per_mile,
  ROUND(AVG(duration_min), 1) AS avg_duration_min,
  ROUND(100.0 * SUM(CASE WHEN payment_type = 1 THEN tip_amount END) / SUM(CASE WHEN payment_type = 1 THEN fare_amount END), 2) AS card_tip_pct
FROM fact_trips GROUP BY 1;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_airports AS
SELECT z.zone AS airport, COUNT(*) AS pickups, ROUND(AVG(f.fare_amount), 2) AS avg_fare,
  ROUND(AVG(f.total_amount), 2) AS avg_total, ROUND(AVG(f.trip_distance), 2) AS avg_distance_mi,
  ROUND(100.0 * AVG(CASE WHEN f.ratecode_id = 2 THEN 1.0 ELSE 0.0 END), 2) AS jfk_flat_fare_pct
FROM fact_trips f JOIN dim_zone z ON z.location_id = f.pu_location_id
WHERE z.is_airport = 1 GROUP BY z.zone;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  before/after counts, DQ issue counts and hard assertions

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'trips' AS entity, (SELECT COUNT(*) FROM stg_trips) AS raw_rows, (SELECT COUNT(*) FROM cln_trips) AS clean_rows,
       (SELECT COUNT(*) FROM stg_trips) - (SELECT COUNT(*) FROM cln_trips) AS removed_rows, 'trip' AS grain
UNION ALL SELECT 'zones', (SELECT COUNT(*) FROM stg_zones), (SELECT COUNT(*) FROM cln_zones), 0, 'TLC location'
UNION ALL SELECT 'fact_trips', NULL, (SELECT COUNT(*) FROM fact_trips), NULL, 'trip'
UNION ALL SELECT 'dim_zone', NULL, (SELECT COUNT(*) FROM dim_zone), NULL, 'zone'
UNION ALL SELECT 'dim_date', NULL, (SELECT COUNT(*) FROM dim_date), NULL, 'day'
UNION ALL SELECT 'dim_payment', NULL, (SELECT COUNT(*) FROM dim_payment), NULL, 'payment type';

-- COMMAND ----------

-- flags overlap, so each count is "rows with this flag" (a trip can fail several rules)

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'pickup outside Jan 2024' AS check_name, (SELECT SUM(dq_outside_month) FROM cln_trips_flagged) AS affected_rows
UNION ALL SELECT 'duration < 1 min or > 3 h (incl. dropoff <= pickup)', (SELECT SUM(dq_bad_duration) FROM cln_trips_flagged)
UNION ALL SELECT 'distance <= 0 or > 100 mi', (SELECT SUM(dq_bad_distance) FROM cln_trips_flagged)
UNION ALL SELECT 'fare <= 0, total <= 0 or fare > $500 (refunds/voids)', (SELECT SUM(dq_bad_amount) FROM cln_trips_flagged)
UNION ALL SELECT 'implied speed > 80 mph', (SELECT SUM(dq_speed_outlier) FROM cln_trips_flagged)
UNION ALL SELECT 'payment_type 0 (flex/unknown; kept, flagged)', (SELECT SUM(dq_unknown_payment) FROM cln_trips_flagged)
UNION ALL SELECT 'passenger_count NULL (kept)', (SELECT COUNT(*) FROM cln_trips_flagged WHERE passenger_count IS NULL)
UNION ALL SELECT 'passenger_count 0 (kept)', (SELECT COUNT(*) FROM cln_trips_flagged WHERE passenger_count = 0)
UNION ALL SELECT 'pickup zone 264/265 (unknown / outside NYC)', (SELECT COUNT(*) FROM cln_trips WHERE pu_location_id IN (264, 265))
UNION ALL SELECT 'total rows removed', (SELECT COUNT(*) FROM stg_trips) - (SELECT COUNT(*) FROM cln_trips);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'every clean trip is in fact_trips' AS check_name, (SELECT COUNT(*) FROM cln_trips) - (SELECT COUNT(*) FROM fact_trips) AS failed_rows
  UNION ALL SELECT 'all pickups within Jan 2024', (SELECT COUNT(*) FROM fact_trips WHERE pickup_ts < TIMESTAMP'2024-01-01 00:00:00' OR pickup_ts >= TIMESTAMP'2024-02-01 00:00:00')
  UNION ALL SELECT 'pickup zone exists in dim_zone', (SELECT COUNT(*) FROM fact_trips f LEFT JOIN dim_zone z ON z.location_id = f.pu_location_id WHERE z.location_id IS NULL)
  UNION ALL SELECT 'dropoff zone exists in dim_zone', (SELECT COUNT(*) FROM fact_trips f LEFT JOIN dim_zone z ON z.location_id = f.do_location_id WHERE z.location_id IS NULL)
  UNION ALL SELECT 'payment type exists in dim_payment', (SELECT COUNT(*) FROM fact_trips f LEFT JOIN dim_payment p ON p.payment_type = f.payment_type WHERE p.payment_type IS NULL)
  UNION ALL SELECT 'date exists in dim_date', (SELECT COUNT(*) FROM fact_trips f LEFT JOIN dim_date d ON d.date_key = f.date_key WHERE d.date_key IS NULL)
  UNION ALL SELECT 'positive fare, distance, duration', (SELECT COUNT(*) FROM fact_trips WHERE fare_amount <= 0 OR trip_distance <= 0 OR duration_min < 1)
  UNION ALL SELECT 'hourly trips sum = fact rows', (SELECT ABS((SELECT SUM(trips) FROM a_hourly) - (SELECT COUNT(*) FROM fact_trips)))
  UNION ALL SELECT 'zone lookup ids unique', (SELECT COUNT(*) - COUNT(DISTINCT location_id) FROM dim_zone)
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visual queries (same as the Lakeview dashboard)

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Trips by pickup hour (bar: x=pickup_hour, y=trips)
SELECT pickup_hour, trips FROM a_hourly ORDER BY pickup_hour;

-- COMMAND ----------

-- Visualization: Trips per day (Jan 2024) (line: x=trip_date, y=trips)
SELECT CAST(trip_date AS STRING) AS trip_date, trips FROM a_daily ORDER BY trip_date;

-- COMMAND ----------

-- Visualization: Top 10 pickup zones (hbar: x=zone, y=trips)
SELECT zone, trips FROM a_pickup_zones ORDER BY trips DESC LIMIT 10;

-- COMMAND ----------

-- Visualization: Fare per mile by trip distance ($) (bar: x=distance_band, y=fare_per_mile)
SELECT distance_band, fare_per_mile FROM a_distance_bands ORDER BY distance_band;

-- COMMAND ----------

-- Visualization: Card tip % of fare by trip distance (bar: x=distance_band, y=card_tip_pct)
SELECT distance_band, card_tip_pct FROM a_distance_bands ORDER BY distance_band;

-- COMMAND ----------

-- Visualization: Share of trips by payment type (%) (hbar: x=payment_name, y=share_pct)
SELECT payment_name, share_pct FROM a_payment ORDER BY share_pct DESC;
